#!/usr/bin/env python3
"""Regenerate ha/sensors/news_sources.yaml from ha/config/news_sources.yaml.

Invoked locally before deploy (or by deploy.sh as a pre-rsync hook).
Each entry in config/news_sources.yaml becomes a command_line sensor that runs
scripts/fetch_rss.sh or scripts/fetch_json.sh with the source-specific URL+path.

Idempotent: always overwrites sensors/news_sources.yaml.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_HA = Path(__file__).resolve().parents[1]
CONFIG = REPO_HA / "config" / "news_sources.yaml"
OUTPUT = REPO_HA / "sensors" / "news_sources.yaml"

HEADER = """# AUTO-GENERATED by ha/scripts/generate_news_sensors.py.
# DO NOT EDIT BY HAND. Edit ha/config/news_sources.yaml and regenerate.
"""


def render(sources: list[dict]) -> str:
    lines: list[str] = [HEADER]
    for src in sources:
        name = src["name"]
        shape = src.get("shape", "rss")
        url = src["url"]
        max_items = src.get("max_items", 5)
        scan = src.get("scan_interval", 1800)
        helper = "fetch_rss.sh" if shape == "rss" else "fetch_json.sh"
        json_path = src.get("json_path", "")
        lines.append(
            f"""
- platform: command_line
  name: news_{name}
  unique_id: news_{name}
  command: "/config/custom/inkplate/scripts/{helper} '{url}' {max_items} '{json_path}'"
  scan_interval: {scan}
  value_template: "{{{{ value_json.count }}}}"
  json_attributes:
    - stories
"""
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    if not CONFIG.exists():
        print(f"ERROR: {CONFIG} missing", file=sys.stderr)
        return 2
    data = yaml.safe_load(CONFIG.read_text()) or {}
    sources = data.get("sources", [])
    if not sources:
        print("WARN: no sources declared; writing placeholder.", file=sys.stderr)
        OUTPUT.write_text(HEADER + "\n[]\n")
        return 0
    OUTPUT.write_text(render(sources))
    print(f"wrote {OUTPUT} ({len(sources)} source(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
