"""One-off: build a static HTML review page for famous-quotes-resolved-deduped.json.

For each entry: stage a temporary sidecar in corpus/texts/_qreview-<n>-<slug>.yaml,
render the production summary face PNG via the test renderer (port 8585), then
delete the sidecar. Final output is a self-contained HTML page with one card
per entry: popular quote, resolved snippet, discrepancy note, predicted tier,
and the device-equivalent PNG.

The temp sidecars use a `_qreview-` id prefix so they're trivially identifiable
if anything goes wrong mid-run (orphan cleanup is `rm corpus/texts/_qreview-*`).

Usage:
  python pairing/research_build_quotes_review.py
  python pairing/research_build_quotes_review.py --limit 5     # smoke test
  python pairing/research_build_quotes_review.py --keep-sidecars  # leave temp YAMLs in place
"""
from __future__ import annotations

import argparse, html as ihtml, json, os, re, sys, time, urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC_DEFAULT = ROOT / "openspec/changes/expand-summary-pool/lists/famous-quotes-curated.json"
REVIEW_DIR = ROOT / "openspec/changes/expand-summary-pool/lists/quotes-review"
PNGS_DIR = REVIEW_DIR / "renders"
HTML_OUT = REVIEW_DIR / "index.html"
TEXTS_DIR = ROOT / "corpus" / "texts"
RENDER_URL = os.environ.get("RENDERER_URL", "http://127.0.0.1:8585") + "/debug/text-summary-test.png"

PREFIX = "_qreview-"
FAKE_PILL = (
    "*Placeholder.* This pill is a stand-in for review purposes — it shows the "
    "cell at production geometry (28u IBM Plex Sans, lh 1.1) without a real "
    "deep-dive. Generated by research_build_quotes_review.py from the famous-"
    "quotes-research candidate list."
)


def slug(s: str, maxlen: int = 30) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", (s or "").lower()).strip("-")
    return s[:maxlen]


def stage_sidecar(idx: int, entry: dict) -> str:
    """Write a temporary sidecar; return its id."""
    sid = f"{PREFIX}{idx:03d}-{slug(entry.get('author',''),12)}-{slug(entry.get('poem_title',''),18)}"
    body = entry["snippet_in_source"]
    doc = {
        "id": sid,
        "title": entry.get("poem_title") or "(untitled)",
        "author": entry.get("author") or "(unknown)",
        "year": entry.get("year"),
        "form": "fragment",
        "language": [entry.get("language") or "en"],
        "rights_tier": "personal_library",
        "text_variants": {entry.get("language") or "en": body + "\n"},
        "themes": ["review"],
        "mood": ["review"],
        "register": ["review"],
        "smart_pill": {"body": FAKE_PILL, "model": "placeholder"},
    }
    path = TEXTS_DIR / f"{sid}.yaml"
    path.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    return sid


def render_png(sid: str, out_path: Path, retries: int = 2) -> str | None:
    """Fetch PNG for sid; return error string or None on success."""
    for attempt in range(retries + 1):
        try:
            with urllib.request.urlopen(f"{RENDER_URL}?id={sid}", timeout=60) as r:
                data = r.read()
            if len(data) < 5000:
                return f"png too small ({len(data)} bytes)"
            out_path.write_bytes(data)
            return None
        except Exception as e:
            if attempt < retries:
                time.sleep(1.5)
                continue
            return f"{type(e).__name__}: {e}"


def build_html(entries: list[dict], renders_rel: str) -> str:
    css = (
        "body{margin:0;font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#f4f4f4;color:#222}"
        "h1{position:sticky;top:0;background:#1a1a1a;color:#fff;margin:0;padding:14px 24px;font-size:16px;z-index:10}"
        ".note{background:#fff;margin:0;padding:12px 24px;color:#555;font-size:13px;border-bottom:1px solid #ddd}"
        ".card{margin:24px auto;width:1200px;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.1)}"
        ".card header{padding:14px 18px;border-bottom:1px solid #eee}"
        ".card h2{margin:0 0 6px 0;font-size:16px}"
        ".meta{margin:0 0 6px 0;font-size:12px;color:#777;font-family:ui-monospace,monospace}"
        ".popular,.snippet{margin:6px 0;padding:8px 12px;font-size:13px;line-height:1.5;border-left:3px solid #d0d0d0;background:#fafafa;white-space:pre-wrap;font-family:Georgia,serif}"
        ".popular{border-left-color:#fa4}"
        ".snippet{border-left-color:#4a8;font-family:ui-monospace,monospace;font-size:12px}"
        ".label{font-size:10px;color:#888;text-transform:uppercase;letter-spacing:.06em;margin-bottom:2px;font-family:ui-monospace,monospace}"
        ".discrepancy{margin:6px 0;padding:6px 12px;font-size:12px;color:#a55;background:#fff7e8;border-left:3px solid #fa4}"
        ".discrepancy.identical{color:#365;background:#eef7ee;border-left-color:#4a8}"
        ".tags{margin-top:6px;font-size:11px;font-family:ui-monospace,monospace}"
        ".tag{display:inline-block;padding:2px 8px;background:#eef;color:#336;border-radius:3px;margin-right:4px}"
        ".tag.tier1,.tag.tier2,.tag.tier3{background:#e0f0e0;color:#163}"
        ".tag.tier4,.tag.tier5{background:#eef7ee;color:#365}"
        ".tag.tier6,.tag.tier7{background:#fee;color:#c33}"
        ".card img{display:block;width:1200px;height:auto}"
    )
    parts = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        f"<title>Famous-quotes review ({len(entries)} entries)</title>",
        f"<style>{css}</style>",
        "</head><body>",
        f"<h1>Famous-quotes review — {len(entries)} entries</h1>",
        "<p class='note'>Each card shows: <b>POPULAR</b> = the quote as commonly shared on the web; "
        "<b>SOURCE</b> = the same lines as they appear in the actual poem (line breaks preserved); "
        "<b>discrepancy</b> = how they differ; <b>tier N</b> = predicted renderer font tier "
        "(tier 1=36u, tier 4=28u pill-parity floor, tier 6/7=sub-pill). The PNG is the device-equivalent "
        "summary face rendered at 1200×825 with a placeholder smart_pill.</p>",
    ]
    for e in entries:
        sid = e["_sidecar_id"]
        png_rel = f"{renders_rel}/{sid}.png" if e.get("_render_ok") else None
        tier = e.get("predicted_tier")
        geom = e.get("snippet_geometry") or {}
        disc = e.get("discrepancy_note") or ""
        is_identical = "identical" in disc.lower()
        parts.append("<section class='card'>")
        parts.append("  <header>")
        parts.append(f"    <h2>{ihtml.escape(e.get('author') or '')} — {ihtml.escape(e.get('poem_title') or '')}</h2>")
        parts.append(f"    <p class='meta'>id: {ihtml.escape(sid)} · year: {e.get('year')} · "
                     f"lang: {e.get('language')} · rights: {e.get('rights_status')}</p>")
        parts.append(f"    <div class='label'>POPULAR (as quoted on the web)</div>")
        parts.append(f"    <div class='popular'>{ihtml.escape(e.get('popular_quote') or '')}</div>")
        parts.append(f"    <div class='label'>SOURCE (as it appears in the actual poem)</div>")
        parts.append(f"    <div class='snippet'>{ihtml.escape(e.get('snippet_in_source') or '')}</div>")
        cls = "discrepancy identical" if is_identical else "discrepancy"
        parts.append(f"    <div class='{cls}'>{ihtml.escape(disc)}</div>")
        if e.get("_curation_note"):
            cs = e.get("_curation_source", "")
            parts.append(f"    <div class='label'>CURATION ({ihtml.escape(cs)})</div>")
            parts.append(f"    <div class='discrepancy identical'>{ihtml.escape(e['_curation_note'])}</div>")
        parts.append("    <div class='tags'>")
        parts.append(f"      <span class='tag tier{tier}'>tier {tier}</span>")
        parts.append(f"      <span class='tag'>{geom.get('n_lines','?')} lines</span>")
        parts.append(f"      <span class='tag'>longest {geom.get('longest_line_chars','?')} chars</span>")
        parts.append(f"      <span class='tag'>{geom.get('total_chars','?')} total chars</span>")
        if e.get("source_text_url"):
            parts.append(f"      <a class='tag' href='{ihtml.escape(e['source_text_url'])}' target='_blank'>source</a>")
        parts.append("    </div>")
        parts.append("  </header>")
        if png_rel:
            parts.append(f"  <img src='{png_rel}' alt='{ihtml.escape(sid)}'>")
        else:
            parts.append(f"  <p class='note' style='color:#c33;padding:12px 18px'>render failed: "
                         f"{ihtml.escape(e.get('_render_error') or 'unknown')}</p>")
        parts.append("</section>")
    parts.append("</body></html>")
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--keep-sidecars", action="store_true",
                    help="don't delete the temp sidecars after rendering (debug)")
    ap.add_argument("--sleep", type=float, default=0.3)
    ap.add_argument("--src", type=Path, default=SRC_DEFAULT,
                    help="JSON source file (default: famous-quotes-curated.json)")
    args = ap.parse_args()

    entries = json.loads(args.src.read_text())
    if args.limit:
        entries = entries[:args.limit]

    REVIEW_DIR.mkdir(parents=True, exist_ok=True)
    PNGS_DIR.mkdir(parents=True, exist_ok=True)

    staged: list[Path] = []
    print(f"Staging {len(entries)} sidecars in {TEXTS_DIR.relative_to(ROOT)}/...")
    for i, e in enumerate(entries, 1):
        sid = stage_sidecar(i, e)
        e["_sidecar_id"] = sid
        staged.append(TEXTS_DIR / f"{sid}.yaml")

    print(f"Rendering PNGs via {RENDER_URL}...")
    ok = err = 0
    try:
        for i, e in enumerate(entries, 1):
            sid = e["_sidecar_id"]
            out = PNGS_DIR / f"{sid}.png"
            res = render_png(sid, out)
            if res is None:
                ok += 1
                e["_render_ok"] = True
            else:
                err += 1
                e["_render_ok"] = False
                e["_render_error"] = res
            if i % 5 == 0 or i == len(entries):
                print(f"  [{i}/{len(entries)}] ok={ok} err={err}")
            time.sleep(args.sleep)
    finally:
        if not args.keep_sidecars:
            for p in staged:
                if p.exists():
                    p.unlink()
            print(f"Cleaned up {len(staged)} temp sidecars.")

    html = build_html(entries, "renders")
    HTML_OUT.write_text(html, encoding="utf-8")
    print(f"\nWrote {HTML_OUT.relative_to(ROOT)} ({len(html):,} chars)")
    print(f"  rendered ok: {ok}, render errors: {err}")
    print(f"\nOpen with: open {HTML_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
